plugins {
    id 'org.springframework.boot' version '3.5.9'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.jetbrains.kotlin.jvm' version '2.1.0'
    id 'org.jetbrains.kotlin.plugin.spring' version '2.1.0'
    id 'org.jetbrains.kotlin.plugin.jpa' version '2.1.0'
    id 'com.epages.restdocs-api-spec' version '0.19.4'
}

group = 'com.flab'
version = '0.0.1'
description = 'license-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    compilerOptions {
        freeCompilerArgs.addAll('-Xjsr305=strict')
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-reflect'
    implementation 'io.github.microutils:kotlin-logging-jvm:3.0.5'
    runtimeOnly 'com.h2database:h2'
    runtimeOnly 'com.mysql:mysql-connector-j'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito.kotlin:mockito-kotlin:5.4.0'
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
    testImplementation 'com.epages:restdocs-api-spec-mockmvc:0.19.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

openapi3 {
    servers = [
            { url = System.getenv('API_SERVER_URL') ?: 'http://localhost:8080' }
    ]
    title = 'License Service API'
    description = '라이선스 관리 서비스 API'
    version = project.version.toString()
    format = 'yaml'
    outputDirectory = layout.buildDirectory.dir('api-spec').get().asFile.path
}

afterEvaluate {
    tasks.named('openapi3') {
        dependsOn 'test'
    }
}

tasks.register('copyOpenApiSpec', Copy) {
    dependsOn 'openapi3'
    from layout.buildDirectory.file('api-spec/openapi3.yaml')
    into 'src/main/resources/static/docs'
    rename { 'openapi.yaml' }
}

bootJar {
    dependsOn 'copyOpenApiSpec'
}
